<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260701000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create report_run table for weekly feedback report idempotency.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE report_run (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, report_name VARCHAR(64) NOT NULL, window_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, window_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recipient VARCHAR(255) NOT NULL, status VARCHAR(16) NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, hash VARCHAR(64) NOT NULL, meta JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_report_run_hash ON report_run (hash)');
        $this->addSql('CREATE INDEX idx_report_run_window ON report_run (window_start, window_end)');
        $this->addSql('CREATE INDEX idx_report_run_report_name ON report_run (report_name)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE report_run');
    }
}
