<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251201173153 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_feedback (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT NOT NULL, rating SMALLINT NOT NULL, main_issue VARCHAR(50) DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_app_feedback_created_at ON app_feedback (created_at)');
        $this->addSql('CREATE INDEX idx_app_feedback_main_issue ON app_feedback (main_issue)');
        $this->addSql('CREATE INDEX idx_app_feedback_rating ON app_feedback (rating)');
        $this->addSql('CREATE TABLE chat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE chat_participants (chat_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (chat_id, user_id))');
        $this->addSql('CREATE INDEX IDX_8F8219131A9A7125 ON chat_participants (chat_id)');
        $this->addSql('CREATE INDEX IDX_8F821913A76ED395 ON chat_participants (user_id)');
        $this->addSql('CREATE TABLE match_feedback (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, match_id INT DEFAULT NULL, target_request_id INT DEFAULT NULL, comment TEXT DEFAULT NULL, reason_code VARCHAR(32) DEFAULT NULL, relevance_score SMALLINT NOT NULL, main_issue VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_match_feedback_created_at ON match_feedback (created_at)');
        $this->addSql('CREATE INDEX idx_match_feedback_reason_code ON match_feedback (reason_code)');
        $this->addSql('CREATE INDEX idx_match_feedback_main_issue ON match_feedback (main_issue)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_read BOOLEAN NOT NULL, chat_id INT NOT NULL, sender_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F1A9A7125 ON message (chat_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FF624B39D ON message (sender_id)');
        $this->addSql('CREATE TABLE refresh_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, refresh_token VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE chat_participants ADD CONSTRAINT FK_8F8219131A9A7125 FOREIGN KEY (chat_id) REFERENCES chat (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_participants ADD CONSTRAINT FK_8F821913A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F1A9A7125 FOREIGN KEY (chat_id) REFERENCES chat (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE request ADD lat DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE request ADD lng DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD email VARCHAR(180) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD roles JSON NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD password VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD lat DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD lng DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chat_participants DROP CONSTRAINT FK_8F8219131A9A7125');
        $this->addSql('ALTER TABLE chat_participants DROP CONSTRAINT FK_8F821913A76ED395');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F1A9A7125');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FF624B39D');
        $this->addSql('DROP TABLE app_feedback');
        $this->addSql('DROP TABLE chat');
        $this->addSql('DROP TABLE chat_participants');
        $this->addSql('DROP TABLE match_feedback');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('ALTER TABLE request DROP lat');
        $this->addSql('ALTER TABLE request DROP lng');
        $this->addSql('DROP INDEX UNIQ_8D93D649E7927C74');
        $this->addSql('ALTER TABLE "user" DROP email');
        $this->addSql('ALTER TABLE "user" DROP roles');
        $this->addSql('ALTER TABLE "user" DROP password');
        $this->addSql('ALTER TABLE "user" DROP lat');
        $this->addSql('ALTER TABLE "user" DROP lng');
    }
}
